/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Archivos;
import Controlador.ClienteFtp;
import Controlador.SSH;
import Modelo.Fecha;
import Modelo.HiloServidorCaido;
import Modelo.variablesGlobales;
import com.jcraft.jsch.JSchException;
import java.awt.event.ActionEvent;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author JULIO
 */
public class VentanaGenRespaldos extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public VentanaGenRespaldos() {
        initComponents();
        this.setLocationRelativeTo(null);
        rsscalelabel.RSScaleLabel.setScaleLabel(logo, "src/Recursos/ABWHIT.png");
        this.txtUsuarioActivo.setText(variablesGlobales.USUARIO_ACTIVO);
        LLenarLista();
        this.txtDispositivoActivo.setSelectedItem(variablesGlobales.DISPOSITIVO_ACTIVO);
        actualizarVariable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnCambiar = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();
        txtDispositivoActivo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        txtUsuarioActivo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnConsultaArchivo = new javax.swing.JButton();
        btnCrearRespaldos = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(204, 0, 0));

        btnCambiar.setBackground(new java.awt.Color(255, 0, 0));
        btnCambiar.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        btnCambiar.setForeground(new java.awt.Color(255, 255, 255));
        btnCambiar.setText("Cambiar");
        btnCambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarActionPerformed(evt);
            }
        });

        btnCerrarSesion.setBackground(new java.awt.Color(255, 0, 0));
        btnCerrarSesion.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        btnCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrarSesion.setText("Logout");
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });

        txtDispositivoActivo.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        txtDispositivoActivo.setEnabled(false);

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Usuario Activo: ");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        txtUsuarioActivo.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        txtUsuarioActivo.setEnabled(false);

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Dispositivo Seleccionado");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnConsultaArchivo.setBackground(new java.awt.Color(255, 0, 0));
        btnConsultaArchivo.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        btnConsultaArchivo.setForeground(new java.awt.Color(255, 255, 255));
        btnConsultaArchivo.setText("Consultar Archivo Respaldo");
        btnConsultaArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaArchivoActionPerformed(evt);
            }
        });

        btnCrearRespaldos.setBackground(new java.awt.Color(255, 0, 0));
        btnCrearRespaldos.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        btnCrearRespaldos.setForeground(new java.awt.Color(255, 255, 255));
        btnCrearRespaldos.setText("Crear Respaldo Configuracion");
        btnCrearRespaldos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearRespaldosActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("MENU RESPALDOS");

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUsuarioActivo, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDispositivoActivo, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(btnCambiar)
                .addGap(18, 18, 18)
                .addComponent(btnCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(343, 343, 343)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCrearRespaldos, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnConsultaArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(logo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDispositivoActivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUsuarioActivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCambiar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(btnConsultaArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(btnCrearRespaldos, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Funcion autogenerada que realiza la accion de cambiar dispositivo
     * seleccionado
     *
     * @author JULIO
     */
    private void btnCambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarActionPerformed
        if (variablesGlobales.ventana != null) {
            variablesGlobales.ventana.setVisible(false);
        }

        this.txtDispositivoActivo.enable(true);
    }//GEN-LAST:event_btnCambiarActionPerformed

    /**
     * Funcion cierra la sesion del usuario logeado
     *
     * @author JULIO
     */
    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        if (variablesGlobales.ventana != null) {
            variablesGlobales.ventana.setVisible(false);
        }
        this.setVisible(false);
        new LoginRespaldos().show();
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    /**
     * Funcion que inicializa la ventana de consultar archivos de respaldos
     *
     * @author JULIO
     */
    private void btnConsultaArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaArchivoActionPerformed
        variablesGlobales.ventana = new ConsultaArchivo();
        variablesGlobales.ventana.show();
    }//GEN-LAST:event_btnConsultaArchivoActionPerformed

    /**
     * Funcion que al presionar el boton realiza las validaciones de los
     * servidores y cre los archivos de respaldo
     *
     * @author JULIO
     */
    private void btnCrearRespaldosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearRespaldosActionPerformed
        try {

            if (Encendido() && !HiloServidorCaido.ServerBaseDatosCaido
                    && !HiloServidorCaido.ServerFTPCaido) {
                String resultado = SSH.ConectarSSh("admin", "admin", variablesGlobales.DISPOSITIVO_DIRECCIONIP, 22, "show run");
                System.out.println(resultado);
                String nombre = variablesGlobales.DISPOSITIVO_ACTIVO + "-" + (new Fecha()).imprimirFechaConHoraySeg();
                Archivos.escribirDatos(resultado, "src/DocumentosGenerados/" + nombre + ".cfg", false);
                ClienteFtp.guardar("src/DocumentosGenerados/" + nombre + ".cfg", nombre + ".cfg");
                try {
                    Archivos.guardarHistorialEvento(variablesGlobales.USUARIO_ACTIVO,
                            (new Fecha()).imprimirFecha(),
                            variablesGlobales.DISPOSITIVO_ACTIVO,
                            "Respaldo", nombre + ".cfg");
                    JOptionPane.showMessageDialog(null, "Respaldo Generado");
                } catch (Exception e) {
                }

            } else {
                try {
                    if (!HiloServidorCaido.ServerBaseDatosCaido) {
                        Archivos.guardarHistorialEvento(variablesGlobales.USUARIO_ACTIVO, (new Fecha()).imprimirFecha(),
                                variablesGlobales.DISPOSITIVO_ACTIVO, "Apagado");

                    } else {
                        JOptionPane.showMessageDialog(null, "Servidor Caido");
                    }
                    if (HiloServidorCaido.ServerFTPCaido) {
                        JOptionPane.showMessageDialog(null, "Servidor Caido");
                    }

                } catch (Exception e) {
                }

            }

        } catch (JSchException | IllegalAccessException | IOException ex) {
            JOptionPane.showMessageDialog(null, "Falla de conexión con el servidor" + ex.getMessage(),
                    "Error de Conexion", JOptionPane.ERROR_MESSAGE);

            Archivos.escribirDatos(variablesGlobales.USUARIO_ACTIVO + ";"
                    + "Error Conexion" + ";" + (new Fecha()).imprimirFecha(), "src/DocumentosGenerados/logs", true);
        }
    }//GEN-LAST:event_btnCrearRespaldosActionPerformed

    /**
     * Hilo que actualiza la variable del dispositivo seleccionado
     *
     * @author JULIO
     */
    private void actualizarVariable() {
        Timer timer = new Timer(1, (ActionEvent e) -> {
            variablesGlobales.DISPOSITIVO_ACTIVO = this.txtDispositivoActivo.getSelectedItem().toString();
        });
        timer.start();
    }

    /**
     * @author Julio Bodero Funcion que valida si el dispositivo esta encendido
     */
    private Boolean Encendido() {
        return "On".equals(variablesGlobales.DISPOSITIVO_ESTADO);
    }

    /**
     * Funcion que añade la lista de dispositivos activos del sistema
     *
     * @author JULIO
     */
    private void LLenarLista() {
        for (String dispositivo : variablesGlobales.dispositivos) {
            this.txtDispositivoActivo.addItem(dispositivo);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaGenRespaldos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaGenRespaldos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaGenRespaldos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaGenRespaldos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new VentanaGenRespaldos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCambiar;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnConsultaArchivo;
    private javax.swing.JButton btnCrearRespaldos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel logo;
    private javax.swing.JComboBox<String> txtDispositivoActivo;
    private javax.swing.JTextField txtUsuarioActivo;
    // End of variables declaration//GEN-END:variables
}
